<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>InWorldz.Phlox</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="C5" HintPath="..\..\Library\C5.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Include="protobuf-net" Version="3.2.56" />
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="StringTemplate4" Version="4.0.8" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenSim.Framework\OpenSim.Framework.csproj" />
    <ProjectReference Include="..\OpenSim.Region.Framework\OpenSim.Region.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Compiler\Def.cs" />
    <Compile Remove="Compiler\Types.cs" />
    <Compile Remove="Compiler\Analyze.cs" />
    <Compile Remove="Compiler\Gen.cs" />
    <compile Remove="Properties\AssemblyInfo.cs" />
    <Compile Remove="grammar/generated/*.cs" />
  </ItemGroup>

</Project>
