<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Condition="!Exists('packages.config')">
      <PrivateAssets>all</PrivateAssets>
      <Version>3.10.91</Version>
    </PackageReference>
    <PackageReference Include="nini-core" Version="0.9.2.16" />
    <PackageReference Include="UtopiaSkye.OpenMetaverse" Version="1.1.6-ga897ffefd7" />
    <PackageReference Include="UtopiaSkye.OpenMetaverse.Types" Version="1.1.6-ga897ffefd7" />
    <PackageReference Include="UtopiaSkye.OpenMetaverse.StructuredData" Version="1.1.6-ga897ffefd7" />
    <PackageReference Include="UtopiaSkye.OpenMetaverse.Rendering.Meshmerizer" Version="1.1.6-ga897ffefd7" />
    <PackageReference Include="UtopiaSkye.OpenMetaverse.Rendering.Simple" Version="1.1.6-ga897ffefd7" />
  </ItemGroup>
</Project>
