<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>OpenSim.Framework.Servers.HttpServer</AssemblyTitle>
    <Company>http://opensimulator.org</Company>
    <Product>OpenSim</Product>
    <Copyright>OpenSimulator developers</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="xmlrpc" HintPath="../../Library/xmlrpc.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Source/OpenSim.Framework/OpenSim.Framework.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Monitoring/OpenSim.Framework.Monitoring.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
  </ItemGroup>

</Project>
