<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>OpenSim.Capabilities.Handlers</AssemblyTitle>
    <Company>http://opensimulator.org</Company>
    <Product>OpenSim</Product>
    <Copyright>OpenSimulator developers</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DotNetOpenId" HintPath="../../Library/DotNetOpenId.dll" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="../../Source/OpenSim.Capabilities/OpenSim.Capabilities.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework/OpenSim.Framework.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Console/OpenSim.Framework.Console.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Servers.HttpServer/OpenSim.Framework.Servers.HttpServer.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Server.Base/OpenSim.Server.Base.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Server.Handlers/OpenSim.Server.Handlers.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Services.Base/OpenSim.Services.Base.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Services.Interfaces/OpenSim.Services.Interfaces.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="CoreJ2K.Skia" Version="2.3.3.91" />
  </ItemGroup>

</Project>
