// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSim.Data.Model.Economy;

#nullable disable

namespace OpenSim.Data.Migrations.Economy
{
    [DbContext(typeof(OpenSimEconomyContext))]
    partial class OpenSimEconomyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenSim.Data.Model.Economy.Balance", b =>
                {
                    b.Property<string>("User")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user");

                    b.Property<int>("Balance1")
                        .HasColumnType("int")
                        .HasColumnName("balance");

                    b.Property<sbyte?>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<sbyte>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("type");

                    b.HasKey("User")
                        .HasName("PRIMARY");

                    b.ToTable("balances", null, t =>
                        {
                            t.HasComment("Rev.4");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Economy.PaymentOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_utc");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_utc");

                    b.Property<int>("CurrencyAmount")
                        .HasColumnType("int")
                        .HasColumnName("currency_amount");

                    b.Property<decimal>("FiatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("fiat_amount");

                    b.Property<string>("FiatCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("fiat_currency");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("gateway");

                    b.Property<string>("GatewayCaptureId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("gateway_capture_id");

                    b.Property<string>("GatewayOrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("gateway_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("Gateway", "GatewayOrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_orders_gateway_order");

                    b.ToTable("payment_orders", (string)null);
                });

            modelBuilder.Entity("OpenSim.Data.Model.Economy.Totalsale", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("UUID");

                    b.Property<string>("ObjectUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("objectUUID");

                    b.Property<int>("Time")
                        .HasColumnType("int")
                        .HasColumnName("time");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.Property<int>("TotalCount")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.ToTable("totalsales", null, t =>
                        {
                            t.HasComment("Rev.3");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Economy.Transaction", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("UUID");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("commonName");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("ObjectName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("objectName");

                    b.Property<string>("ObjectUuid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("objectUUID");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("receiver");

                    b.Property<int>("ReceiverBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("receiverBalance")
                        .HasDefaultValueSql("'-1'");

                    b.Property<string>("RegionHandle")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("regionHandle");

                    b.Property<string>("RegionUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("regionUUID");

                    b.Property<string>("Secure")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("secure");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("sender");

                    b.Property<int>("SenderBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("senderBalance")
                        .HasDefaultValueSql("'-1'");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status");

                    b.Property<int>("Time")
                        .HasColumnType("int")
                        .HasColumnName("time");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasComment("Rev.12");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Economy.Userinfo", b =>
                {
                    b.Property<string>("User")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("avatar");

                    b.Property<sbyte>("Class")
                        .HasColumnType("tinyint")
                        .HasColumnName("class");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("pass")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Serverurl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("serverurl")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Simip")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("simip");

                    b.Property<sbyte>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("type");

                    b.HasKey("User")
                        .HasName("PRIMARY");

                    b.ToTable("userinfo", null, t =>
                        {
                            t.HasComment("Rev.3");
                        });

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });
#pragma warning restore 612, 618
        }
    }
}
