<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>OpenSim.Region.PhysicsModules.ubODEMeshing</AssemblyTitle>
    <Company>http://opensimulator.org</Company>
    <Product>OpenSim</Product>
    <Description>Mesher for ubODE</Description>
    <Copyright>OpenSimulator developers</Copyright>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.10" />
    <PackageReference Include="CoreJ2K.Skia" Version="2.1.0.101" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="Nini" HintPath="../../Library/Nini.dll" />
    <Reference Include="OpenMetaverse" HintPath="../../Library/OpenMetaverse.dll" />
    <Reference Include="OpenMetaverse.StructuredData" HintPath="../../Library/OpenMetaverse.StructuredData.dll" />
    <Reference Include="OpenMetaverseTypes" HintPath="../../Library/OpenMetaverseTypes.dll" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="../../Source/OpenSim.Framework/OpenSim.Framework.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Console/OpenSim.Framework.Console.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Region.Framework/OpenSim.Region.Framework.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Region.PhysicsModules.ConvexDecompositionDotNet/OpenSim.Region.PhysicsModules.ConvexDecompositionDotNet.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Region.PhysicsModules.SharedBase/OpenSim.Region.PhysicsModules.SharedBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/OpenSim.Region.PhysicsModules.ubODEMeshing.addin.xml" />
  </ItemGroup>

</Project>
