<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Nini" HintPath="../../Library/Nini.dll" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="../../Source/OpenSim.Framework/OpenSim.Framework.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Console/OpenSim.Framework.Console.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Servers/OpenSim.Framework.Servers.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Servers.HttpServer/OpenSim.Framework.Servers.HttpServer.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Server.Base/OpenSim.Server.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenMetaverse" Version="1.2.13" />
    <PackageReference Include="OpenMetaverse.Types" Version="1.2.13" />
    <PackageReference Include="OpenMetaverse.StructuredData" Version="1.2.13" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
  </ItemGroup>
</Project>
