// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSim.Data.Model.Search;

#nullable disable

namespace OpenSim.Data.Migrations.Search
{
    [DbContext(typeof(OpenSimSearchContext))]
    partial class OpenSimSearchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenSim.Data.Model.Search.Allparcel", b =>
                {
                    b.Property<string>("ParcelUuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("parcelUUID")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<string>("GatekeeperUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gatekeeperURL");

                    b.Property<string>("GroupUuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("groupUUID")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<string>("InfoUuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("infoUUID")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<string>("Landingpoint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("landingpoint");

                    b.Property<string>("OwnerUuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ownerUUID")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<int>("Parcelarea")
                        .HasColumnType("int")
                        .HasColumnName("parcelarea");

                    b.Property<string>("Parcelname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("parcelname");

                    b.Property<string>("RegionUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("regionUUID")
                        .IsFixedLength();

                    b.HasKey("ParcelUuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RegionUuid" }, "regionUUID");

                    b.ToTable("allparcels", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_unicode_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Search.Classified", b =>
                {
                    b.Property<string>("Classifieduuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("classifieduuid")
                        .IsFixedLength();

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("category");

                    b.Property<int>("Classifiedflags")
                        .HasColumnType("int")
                        .HasColumnName("classifiedflags");

                    b.Property<int>("Creationdate")
                        .HasColumnType("int")
                        .HasColumnName("creationdate");

                    b.Property<string>("Creatoruuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("creatoruuid")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Expirationdate")
                        .HasColumnType("int")
                        .HasColumnName("expirationdate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Parcelname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("parcelname");

                    b.Property<string>("Parceluuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("parceluuid")
                        .IsFixedLength();

                    b.Property<int>("Parentestate")
                        .HasColumnType("int")
                        .HasColumnName("parentestate");

                    b.Property<string>("Posglobal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("posglobal");

                    b.Property<int>("Priceforlisting")
                        .HasColumnType("int")
                        .HasColumnName("priceforlisting");

                    b.Property<string>("Simname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("simname");

                    b.Property<string>("Snapshotuuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("snapshotuuid")
                        .IsFixedLength();

                    b.HasKey("Classifieduuid")
                        .HasName("PRIMARY");

                    b.ToTable("classifieds", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_unicode_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Search.Event", b =>
                {
                    b.Property<uint>("Eventid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("eventid");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Eventid"));

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<int>("Coveramount")
                        .HasColumnType("int")
                        .HasColumnName("coveramount");

                    b.Property<bool>("Covercharge")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("covercharge");

                    b.Property<string>("Creatoruuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("creatoruuid")
                        .IsFixedLength();

                    b.Property<int>("DateUtc")
                        .HasColumnType("int")
                        .HasColumnName("dateUTC");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("Eventflags")
                        .HasColumnType("int")
                        .HasColumnName("eventflags");

                    b.Property<string>("GatekeeperUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gatekeeperURL");

                    b.Property<string>("GlobalPos")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("globalPos");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Owneruuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("owneruuid")
                        .IsFixedLength();

                    b.Property<string>("ParcelUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("parcelUUID")
                        .IsFixedLength();

                    b.Property<string>("Simname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("simname");

                    b.HasKey("Eventid")
                        .HasName("PRIMARY");

                    b.ToTable("events", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Search.Hostsregister", b =>
                {
                    b.Property<string>("Host")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("host");

                    b.Property<int>("Port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.Property<bool>("Checked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("checked");

                    b.Property<int>("Failcounter")
                        .HasColumnType("int")
                        .HasColumnName("failcounter");

                    b.Property<string>("GatekeeperUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gatekeeperURL");

                    b.Property<int>("Nextcheck")
                        .HasColumnType("int")
                        .HasColumnName("nextcheck");

                    b.Property<int>("Register")
                        .HasColumnType("int")
                        .HasColumnName("register");

                    b.HasKey("Host", "Port")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("hostsregister", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_unicode_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Search.Parcel", b =>
                {
                    b.Property<string>("RegionUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("regionUUID")
                        .IsFixedLength();

                    b.Property<string>("ParcelUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("parcelUUID")
                        .IsFixedLength();

                    b.Property<string>("Build")
                        .IsRequired()
                        .HasColumnType("enum('true','false')")
                        .HasColumnName("build");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<float>("Dwell")
                        .HasColumnType("float")
                        .HasColumnName("dwell");

                    b.Property<string>("GatekeeperUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gatekeeperURL");

                    b.Property<string>("ImageUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("imageUUID")
                        .IsFixedLength();

                    b.Property<string>("Infouuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("infouuid")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Landingpoint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("landingpoint");

                    b.Property<string>("Mature")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mature")
                        .HasDefaultValueSql("'PG'");

                    b.Property<string>("Parcelname")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("parcelname");

                    b.Property<string>("Public")
                        .IsRequired()
                        .HasColumnType("enum('true','false')")
                        .HasColumnName("public");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("enum('true','false')")
                        .HasColumnName("script");

                    b.Property<string>("Searchcategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("searchcategory");

                    b.HasKey("RegionUuid", "ParcelUuid")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "Description" }, "description");

                    b.HasIndex(new[] { "Dwell" }, "dwell");

                    b.HasIndex(new[] { "Parcelname" }, "name");

                    b.HasIndex(new[] { "Searchcategory" }, "searchcategory");

                    b.ToTable("parcels", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_unicode_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Search.Parcelsale", b =>
                {
                    b.Property<string>("RegionUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("regionUUID")
                        .IsFixedLength();

                    b.Property<string>("ParcelUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("parcelUUID")
                        .IsFixedLength();

                    b.Property<int>("Area")
                        .HasColumnType("int")
                        .HasColumnName("area");

                    b.Property<int>("Dwell")
                        .HasColumnType("int")
                        .HasColumnName("dwell");

                    b.Property<string>("GatekeeperUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gatekeeperURL");

                    b.Property<string>("InfoUuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("infoUUID")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<string>("Landingpoint")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("landingpoint");

                    b.Property<string>("Mature")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mature")
                        .HasDefaultValueSql("'PG'");

                    b.Property<string>("Parcelname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("parcelname");

                    b.Property<int>("Parentestate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("parentestate")
                        .HasDefaultValueSql("'1'");

                    b.Property<int>("Saleprice")
                        .HasColumnType("int")
                        .HasColumnName("saleprice");

                    b.HasKey("RegionUuid", "ParcelUuid")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("parcelsales", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_unicode_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Search.Popularplace", b =>
                {
                    b.Property<string>("ParcelUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("parcelUUID")
                        .IsFixedLength();

                    b.Property<float>("Dwell")
                        .HasColumnType("float")
                        .HasColumnName("dwell");

                    b.Property<string>("GatekeeperUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gatekeeperURL");

                    b.Property<bool>("HasPicture")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_picture");

                    b.Property<string>("InfoUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("infoUUID")
                        .IsFixedLength();

                    b.Property<string>("Mature")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("mature");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("ParcelUuid")
                        .HasName("PRIMARY");

                    b.ToTable("popularplaces", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_unicode_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Search.Region", b =>
                {
                    b.Property<string>("RegionUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("regionUUID")
                        .IsFixedLength();

                    b.Property<string>("GatekeeperUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gatekeeperURL");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("owner");

                    b.Property<string>("Owneruuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("owneruuid")
                        .IsFixedLength();

                    b.Property<string>("Regionhandle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("regionhandle");

                    b.Property<string>("Regionname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("regionname");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("url");

                    b.HasKey("RegionUuid")
                        .HasName("PRIMARY");

                    b.ToTable("regions", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_unicode_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Search.SearchObject", b =>
                {
                    b.Property<string>("Objectuuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("objectuuid")
                        .IsFixedLength();

                    b.Property<string>("Parceluuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("parceluuid")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("GatekeeperUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("gatekeeperURL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Regionuuid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("regionuuid")
                        .HasDefaultValueSql("''")
                        .IsFixedLength();

                    b.HasKey("Objectuuid", "Parceluuid")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("objects", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_unicode_ci");
                });
#pragma warning restore 612, 618
        }
    }
}
