<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>OpenSimSearch.Modules</AssemblyTitle>
    <Product>OpenSim</Product>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenMetaverse" Version="1.2.13" />
    <PackageReference Include="OpenMetaverse.Types" Version="1.2.13" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.8" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="xmlrpc" HintPath="..\..\Library\xmlrpc.dll" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Source\OpenSim.Data\OpenSim.Data.csproj" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework\OpenSim.Framework.csproj" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework.Console\OpenSim.Framework.Console.csproj" />
    <ProjectReference Include="..\..\Source\OpenSim.Framework.Servers\OpenSim.Framework.Servers.csproj" />
    <ProjectReference Include="..\..\Source\OpenSim.Region.Framework\OpenSim.Region.Framework.csproj" />
    <ProjectReference Include="..\..\Source\OpenSim.Services.Interfaces\OpenSim.Services.Interfaces.csproj" />
  </ItemGroup>
    
</Project>
