<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>OpenSim.Region.PhysicsModules.BulletS</AssemblyTitle>
    <Company>http://opensimulator.org</Company>
    <Product>OpenSim</Product>
    <Copyright>OpenSimulator developers</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Nini.dll" HintPath="../../Library/Nini.dll" />
    <Reference Include="OpenMetaverse.dll" HintPath="../../Library/OpenMetaverse.dll" />
    <Reference Include="OpenMetaverseTypes" HintPath="../../Library/OpenMetaverseTypes.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Source/OpenSim.Framework/OpenSim.Framework.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Console/OpenSim.Framework.Console.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Monitoring/OpenSim.Framework.Monitoring.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Region.Framework/OpenSim.Region.Framework.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Region.PhysicsModules.Meshing/OpenSim.Region.PhysicsModules.Meshing.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Region.PhysicsModules.ConvexDecompositionDotNet/OpenSim.Region.PhysicsModules.ConvexDecompositionDotNet.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Region.PhysicsModules.SharedBase/OpenSim.Region.PhysicsModules.SharedBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.0" />
    <PackageReference Include="Mono.Addins" Version="1.4.1" />
    <PackageReference Include="Mono.Addins.CecilReflector" Version="1.4.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <!-- <Content Include="app.config">
      <Link>$(TargetName).dll.config</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content> -->

    <!-- Reference the managed DLL -->
    <Reference Include="BulletXNA.dll" HintPath="../../Library/BulletXNA.dll" />
    
    <!-- Include the native DLL/SO and copy to output -->
    <Content Include="runtimes\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>