// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSim.Data.Model.Region;

#nullable disable

namespace OpenSim.Data.Migrations.Region
{
    [DbContext(typeof(OpenSimRegionContext))]
    [Migration("20251224213749_InitialCreate_Region")]
    partial class InitialCreate_Region
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenSim.Data.Model.Region.Bakedterrain", b =>
                {
                    b.Property<byte[]>("Heightfield")
                        .HasColumnType("longblob");

                    b.Property<string>("RegionUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RegionUUID");

                    b.Property<int?>("Revision")
                        .HasColumnType("int");

                    b.ToTable("bakedterrain", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Land", b =>
                {
                    b.Property<string>("Uuid")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UUID");

                    b.Property<sbyte>("AnyAvsounds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("AnyAVSounds")
                        .HasDefaultValueSql("'1'");

                    b.Property<int?>("Area")
                        .HasColumnType("int");

                    b.Property<int?>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("AuctionID");

                    b.Property<string>("AuthbuyerId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("AuthbuyerID")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.Property<byte[]>("Bitmap")
                        .HasColumnType("longblob");

                    b.Property<int?>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("ClaimDate")
                        .HasColumnType("int");

                    b.Property<int?>("ClaimPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Dwell")
                        .HasColumnType("int");

                    b.Property<string>("Environment")
                        .HasColumnType("mediumtext")
                        .HasColumnName("environment");

                    b.Property<sbyte>("GroupAvsounds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("GroupAVSounds")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("GroupUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("GroupUUID");

                    b.Property<int?>("IsGroupOwned")
                        .HasColumnType("int");

                    b.Property<uint?>("LandFlags")
                        .HasColumnType("int unsigned");

                    b.Property<int?>("LandStatus")
                        .HasColumnType("int");

                    b.Property<int?>("LandingType")
                        .HasColumnType("int");

                    b.Property<int?>("LocalLandId")
                        .HasColumnType("int")
                        .HasColumnName("LocalLandID");

                    b.Property<int?>("MediaAutoScale")
                        .HasColumnType("int");

                    b.Property<string>("MediaDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("''");

                    b.Property<bool>("MediaLoop")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MediaSize")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValueSql("'0,0'");

                    b.Property<string>("MediaTextureUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MediaTextureUUID");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValueSql("'none/none'");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MediaURL");

                    b.Property<string>("MusicUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MusicURL");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("ObscureMedia")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ObscureMusic")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OtherCleanTime")
                        .HasColumnType("int");

                    b.Property<string>("OwnerUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("OwnerUUID");

                    b.Property<float?>("PassHours")
                        .HasColumnType("float");

                    b.Property<int?>("PassPrice")
                        .HasColumnType("int");

                    b.Property<string>("RegionUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RegionUUID");

                    b.Property<int?>("SalePrice")
                        .HasColumnType("int");

                    b.Property<sbyte>("SeeAvs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasColumnName("SeeAVs")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("SnapshotUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("SnapshotUUID");

                    b.Property<float?>("UserLocationX")
                        .HasColumnType("float");

                    b.Property<float?>("UserLocationY")
                        .HasColumnType("float");

                    b.Property<float?>("UserLocationZ")
                        .HasColumnType("float");

                    b.Property<float?>("UserLookAtX")
                        .HasColumnType("float");

                    b.Property<float?>("UserLookAtY")
                        .HasColumnType("float");

                    b.Property<float?>("UserLookAtZ")
                        .HasColumnType("float");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.ToTable("land", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Landaccesslist", b =>
                {
                    b.Property<string>("AccessUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AccessUUID");

                    b.Property<int>("Expires")
                        .HasColumnType("int");

                    b.Property<int?>("Flags")
                        .HasColumnType("int");

                    b.Property<string>("LandUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LandUUID");

                    b.ToTable("landaccesslist", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Migration", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.ToTable("migrations", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Prim", b =>
                {
                    b.Property<string>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("UUID")
                        .HasDefaultValueSql("''")
                        .IsFixedLength();

                    b.Property<float>("AccelerationX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("AccelerationY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("AccelerationZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte>("AllowUnsit")
                        .HasColumnType("tinyint")
                        .HasColumnName("allowunsit");

                    b.Property<sbyte>("AllowedDrop")
                        .HasColumnType("tinyint");

                    b.Property<float>("AngularVelocityX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("AngularVelocityY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("AngularVelocityZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("AttachedPosX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("AttachedPosY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("AttachedPosZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<int?>("BaseMask")
                        .HasColumnType("int");

                    b.Property<float>("CameraAtOffsetX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("CameraAtOffsetY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("CameraAtOffsetZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("CameraEyeOffsetX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("CameraEyeOffsetY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("CameraEyeOffsetZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte>("ClickAction")
                        .HasColumnType("tinyint");

                    b.Property<string>("CollisionSound")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<double>("CollisionSoundVolume")
                        .HasColumnType("double");

                    b.Property<int>("ColorA")
                        .HasColumnType("int");

                    b.Property<int>("ColorB")
                        .HasColumnType("int");

                    b.Property<int>("ColorG")
                        .HasColumnType("int");

                    b.Property<int>("ColorR")
                        .HasColumnType("int");

                    b.Property<int?>("CreationDate")
                        .HasColumnType("int");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CreatorID")
                        .HasDefaultValueSql("''");

                    b.Property<float>("Density")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'1000'");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Description"), "utf8mb3");

                    b.Property<sbyte>("DieAtEdge")
                        .HasColumnType("tinyint");

                    b.Property<string>("DynAttrs")
                        .HasColumnType("text");

                    b.Property<int?>("EveryoneMask")
                        .HasColumnType("int");

                    b.Property<sbyte>("ForceMouselook")
                        .HasColumnType("tinyint");

                    b.Property<float>("Friction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0.6'");

                    b.Property<float>("GravityModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'1'");

                    b.Property<string>("GroupId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("GroupID")
                        .IsFixedLength();

                    b.Property<int?>("GroupMask")
                        .HasColumnType("int");

                    b.Property<float>("GroupPositionX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("GroupPositionY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("GroupPositionZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<byte[]>("KeyframeMotion")
                        .HasColumnType("blob");

                    b.Property<string>("LastOwnerId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("LastOwnerID")
                        .IsFixedLength();

                    b.Property<int>("LinkNumber")
                        .HasColumnType("int");

                    b.Property<string>("LinksetData")
                        .HasColumnType("mediumtext")
                        .HasColumnName("linksetdata");

                    b.Property<string>("LoopedSound")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<float>("LoopedSoundGain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<sbyte>("Material")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("'3'");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MediaURL");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb3");

                    b.Property<int?>("NextOwnerMask")
                        .HasColumnType("int");

                    b.Property<int?>("ObjectFlags")
                        .HasColumnType("int");

                    b.Property<float>("OmegaX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("OmegaY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("OmegaZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("OwnerID")
                        .IsFixedLength();

                    b.Property<int?>("OwnerMask")
                        .HasColumnType("int");

                    b.Property<byte[]>("ParticleSystem")
                        .HasColumnType("blob");

                    b.Property<sbyte>("PassCollisions")
                        .HasColumnType("tinyint");

                    b.Property<sbyte>("PassTouches")
                        .HasColumnType("tinyint");

                    b.Property<int>("PayButton1")
                        .HasColumnType("int");

                    b.Property<int>("PayButton2")
                        .HasColumnType("int");

                    b.Property<int>("PayButton3")
                        .HasColumnType("int");

                    b.Property<int>("PayButton4")
                        .HasColumnType("int");

                    b.Property<int>("PayPrice")
                        .HasColumnType("int");

                    b.Property<string>("PhysInertia")
                        .HasColumnType("text");

                    b.Property<sbyte>("PhysicsShapeType")
                        .HasColumnType("tinyint");

                    b.Property<float>("PositionX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("PositionY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("PositionZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("Pseudocrc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pseudocrc")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("RegionUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("RegionUUID")
                        .IsFixedLength();

                    b.Property<float>("Restitution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0.5'");

                    b.Property<string>("RezzerId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("RezzerID")
                        .IsFixedLength();

                    b.Property<sbyte>("RotationAxisLocks")
                        .HasColumnType("tinyint");

                    b.Property<float>("RotationW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("RotationX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("RotationY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("RotationZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<int>("SalePrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("'10'");

                    b.Property<sbyte>("SaleType")
                        .HasColumnType("tinyint");

                    b.Property<string>("SceneGroupId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("SceneGroupID")
                        .IsFixedLength();

                    b.Property<int>("ScriptAccessPin")
                        .HasColumnType("int");

                    b.Property<sbyte>("ScriptedSitOnly")
                        .HasColumnType("tinyint")
                        .HasColumnName("scriptedsitonly");

                    b.Property<string>("SitName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SitName"), "utf8mb3");

                    b.Property<float>("SitTargetOffsetX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("SitTargetOffsetY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("SitTargetOffsetZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("SitTargetOrientW")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("SitTargetOrientX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("SitTargetOrientY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("SitTargetOrientZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("Sitactrange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasColumnName("sitactrange")
                        .HasDefaultValueSql("'0'");

                    b.Property<byte[]>("Sopanims")
                        .HasColumnType("blob")
                        .HasColumnName("sopanims");

                    b.Property<float>("Standtargetx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasColumnName("standtargetx")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("Standtargety")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasColumnName("standtargety")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("Standtargetz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasColumnName("standtargetz")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("StartStr")
                        .HasColumnType("text")
                        .HasColumnName("startstr");

                    b.Property<string>("Text")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Text"), "utf8mb3");

                    b.Property<byte[]>("TextureAnimation")
                        .HasColumnType("blob");

                    b.Property<string>("TouchName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TouchName"), "utf8mb3");

                    b.Property<string>("Vehicle")
                        .HasColumnType("text");

                    b.Property<float>("VelocityX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("VelocityY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.Property<float>("VelocityZ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("'0'");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RegionUuid" }, "prims_regionuuid");

                    b.HasIndex(new[] { "SceneGroupId" }, "prims_scenegroupid");

                    b.ToTable("prims", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Primitem", b =>
                {
                    b.Property<string>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("itemID")
                        .HasDefaultValueSql("''")
                        .IsFixedLength();

                    b.Property<string>("AssetId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("assetID")
                        .IsFixedLength();

                    b.Property<int?>("AssetType")
                        .HasColumnType("int")
                        .HasColumnName("assetType");

                    b.Property<int?>("BasePermissions")
                        .HasColumnType("int")
                        .HasColumnName("basePermissions");

                    b.Property<long?>("CreationDate")
                        .HasColumnType("bigint")
                        .HasColumnName("creationDate");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CreatorID")
                        .HasDefaultValueSql("''");

                    b.Property<int?>("CurrentPermissions")
                        .HasColumnType("int")
                        .HasColumnName("currentPermissions");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("EveryonePermissions")
                        .HasColumnType("int")
                        .HasColumnName("everyonePermissions");

                    b.Property<int>("Flags")
                        .HasColumnType("int")
                        .HasColumnName("flags");

                    b.Property<string>("GroupId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("groupID")
                        .IsFixedLength();

                    b.Property<int?>("GroupPermissions")
                        .HasColumnType("int")
                        .HasColumnName("groupPermissions");

                    b.Property<int?>("InvType")
                        .HasColumnType("int")
                        .HasColumnName("invType");

                    b.Property<string>("LastOwnerId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("lastOwnerID")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("NextPermissions")
                        .HasColumnType("int")
                        .HasColumnName("nextPermissions");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("ownerID")
                        .IsFixedLength();

                    b.Property<string>("ParentFolderId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("parentFolderID")
                        .IsFixedLength();

                    b.Property<string>("PrimId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("primID")
                        .IsFixedLength();

                    b.HasKey("ItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PrimId" }, "primitems_primid");

                    b.ToTable("primitems", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Primshape", b =>
                {
                    b.Property<string>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("UUID")
                        .HasDefaultValueSql("''")
                        .IsFixedLength();

                    b.Property<byte[]>("ExtraParams")
                        .HasColumnType("longblob");

                    b.Property<int>("LastAttachPoint")
                        .HasColumnType("int");

                    b.Property<byte[]>("MatOvrd")
                        .HasColumnType("blob");

                    b.Property<string>("Media")
                        .HasColumnType("text");

                    b.Property<int?>("PathBegin")
                        .HasColumnType("int");

                    b.Property<int?>("PathCurve")
                        .HasColumnType("int");

                    b.Property<int?>("PathEnd")
                        .HasColumnType("int");

                    b.Property<int?>("PathRadiusOffset")
                        .HasColumnType("int");

                    b.Property<int?>("PathRevolutions")
                        .HasColumnType("int");

                    b.Property<int?>("PathScaleX")
                        .HasColumnType("int");

                    b.Property<int?>("PathScaleY")
                        .HasColumnType("int");

                    b.Property<int?>("PathShearX")
                        .HasColumnType("int");

                    b.Property<int?>("PathShearY")
                        .HasColumnType("int");

                    b.Property<int?>("PathSkew")
                        .HasColumnType("int");

                    b.Property<int?>("PathTaperX")
                        .HasColumnType("int");

                    b.Property<int?>("PathTaperY")
                        .HasColumnType("int");

                    b.Property<int?>("PathTwist")
                        .HasColumnType("int");

                    b.Property<int?>("PathTwistBegin")
                        .HasColumnType("int");

                    b.Property<int?>("Pcode")
                        .HasColumnType("int")
                        .HasColumnName("PCode");

                    b.Property<int?>("ProfileBegin")
                        .HasColumnType("int");

                    b.Property<int?>("ProfileCurve")
                        .HasColumnType("int");

                    b.Property<int?>("ProfileEnd")
                        .HasColumnType("int");

                    b.Property<int?>("ProfileHollow")
                        .HasColumnType("int");

                    b.Property<double>("ScaleX")
                        .HasColumnType("double");

                    b.Property<double>("ScaleY")
                        .HasColumnType("double");

                    b.Property<double>("ScaleZ")
                        .HasColumnType("double");

                    b.Property<int?>("Shape")
                        .HasColumnType("int");

                    b.Property<int?>("State")
                        .HasColumnType("int");

                    b.Property<byte[]>("Texture")
                        .HasColumnType("longblob");

                    b.HasKey("Uuid")
                        .HasName("PRIMARY");

                    b.ToTable("primshapes", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Regionban", b =>
                {
                    b.Property<string>("BannedIp")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("bannedIp");

                    b.Property<string>("BannedIpHostMask")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("bannedIpHostMask");

                    b.Property<string>("BannedUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("bannedUUID");

                    b.Property<string>("RegionUuid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("regionUUID");

                    b.ToTable("regionban", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Regionenvironment", b =>
                {
                    b.Property<string>("RegionId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("region_id");

                    b.Property<string>("LlsdSettings")
                        .HasColumnType("mediumtext")
                        .HasColumnName("llsd_settings");

                    b.HasKey("RegionId")
                        .HasName("PRIMARY");

                    b.ToTable("regionenvironment", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Regionextra", b =>
                {
                    b.Property<string>("RegionId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("RegionID")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("RegionId", "Name")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("regionextra", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Regionsetting", b =>
                {
                    b.Property<string>("RegionUuid")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("regionUUID")
                        .IsFixedLength();

                    b.Property<int>("AgentLimit")
                        .HasColumnType("int")
                        .HasColumnName("agent_limit");

                    b.Property<int>("AllowDamage")
                        .HasColumnType("int")
                        .HasColumnName("allow_damage");

                    b.Property<int>("AllowLandJoinDivide")
                        .HasColumnType("int")
                        .HasColumnName("allow_land_join_divide");

                    b.Property<int>("AllowLandResell")
                        .HasColumnType("int")
                        .HasColumnName("allow_land_resell");

                    b.Property<int>("BlockFly")
                        .HasColumnType("int")
                        .HasColumnName("block_fly");

                    b.Property<sbyte>("BlockSearch")
                        .HasColumnType("tinyint")
                        .HasColumnName("block_search");

                    b.Property<int>("BlockShowInSearch")
                        .HasColumnType("int")
                        .HasColumnName("block_show_in_search");

                    b.Property<int>("BlockTerraform")
                        .HasColumnType("int")
                        .HasColumnName("block_terraform");

                    b.Property<string>("CacheId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("cacheID")
                        .IsFixedLength();

                    b.Property<sbyte>("Casino")
                        .HasColumnType("tinyint")
                        .HasColumnName("casino");

                    b.Property<string>("Covenant")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("covenant")
                        .IsFixedLength();

                    b.Property<uint>("CovenantDatetime")
                        .HasColumnType("int unsigned")
                        .HasColumnName("covenant_datetime");

                    b.Property<int>("DisableCollisions")
                        .HasColumnType("int")
                        .HasColumnName("disable_collisions");

                    b.Property<int>("DisablePhysics")
                        .HasColumnType("int")
                        .HasColumnName("disable_physics");

                    b.Property<int>("DisableScripts")
                        .HasColumnType("int")
                        .HasColumnName("disable_scripts");

                    b.Property<double>("Elevation1Ne")
                        .HasColumnType("double")
                        .HasColumnName("elevation_1_ne");

                    b.Property<double>("Elevation1Nw")
                        .HasColumnType("double")
                        .HasColumnName("elevation_1_nw");

                    b.Property<double>("Elevation1Se")
                        .HasColumnType("double")
                        .HasColumnName("elevation_1_se");

                    b.Property<double>("Elevation1Sw")
                        .HasColumnType("double")
                        .HasColumnName("elevation_1_sw");

                    b.Property<double>("Elevation2Ne")
                        .HasColumnType("double")
                        .HasColumnName("elevation_2_ne");

                    b.Property<double>("Elevation2Nw")
                        .HasColumnType("double")
                        .HasColumnName("elevation_2_nw");

                    b.Property<double>("Elevation2Se")
                        .HasColumnType("double")
                        .HasColumnName("elevation_2_se");

                    b.Property<double>("Elevation2Sw")
                        .HasColumnType("double")
                        .HasColumnName("elevation_2_sw");

                    b.Property<int>("FixedSun")
                        .HasColumnType("int")
                        .HasColumnName("fixed_sun");

                    b.Property<uint>("LoadedCreationDatetime")
                        .HasColumnType("int unsigned")
                        .HasColumnName("loaded_creation_datetime");

                    b.Property<string>("LoadedCreationId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("loaded_creation_id");

                    b.Property<string>("MapTileId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("map_tile_ID")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<int>("Maturity")
                        .HasColumnType("int")
                        .HasColumnName("maturity");

                    b.Property<double>("ObjectBonus")
                        .HasColumnType("double")
                        .HasColumnName("object_bonus");

                    b.Property<string>("ParcelTileId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("parcel_tile_ID")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<int>("RestrictPushing")
                        .HasColumnType("int")
                        .HasColumnName("restrict_pushing");

                    b.Property<sbyte>("Sandbox")
                        .HasColumnType("tinyint");

                    b.Property<double>("SunPosition")
                        .HasColumnType("double")
                        .HasColumnName("sun_position");

                    b.Property<double>("Sunvectorx")
                        .HasColumnType("double")
                        .HasColumnName("sunvectorx");

                    b.Property<double>("Sunvectory")
                        .HasColumnType("double")
                        .HasColumnName("sunvectory");

                    b.Property<double>("Sunvectorz")
                        .HasColumnType("double")
                        .HasColumnName("sunvectorz");

                    b.Property<string>("TelehubObject")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'");

                    b.Property<double>("TerrainLowerLimit")
                        .HasColumnType("double")
                        .HasColumnName("terrain_lower_limit");

                    b.Property<string>("TerrainPbr1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("TerrainPBR1")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<string>("TerrainPbr2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("TerrainPBR2")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<string>("TerrainPbr3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("TerrainPBR3")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<string>("TerrainPbr4")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("TerrainPBR4")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .IsFixedLength();

                    b.Property<double>("TerrainRaiseLimit")
                        .HasColumnType("double")
                        .HasColumnName("terrain_raise_limit");

                    b.Property<string>("TerrainTexture1")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("terrain_texture_1")
                        .IsFixedLength();

                    b.Property<string>("TerrainTexture2")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("terrain_texture_2")
                        .IsFixedLength();

                    b.Property<string>("TerrainTexture3")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("terrain_texture_3")
                        .IsFixedLength();

                    b.Property<string>("TerrainTexture4")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("terrain_texture_4")
                        .IsFixedLength();

                    b.Property<int>("UseEstateSun")
                        .HasColumnType("int")
                        .HasColumnName("use_estate_sun");

                    b.Property<double>("WaterHeight")
                        .HasColumnType("double")
                        .HasColumnName("water_height");

                    b.HasKey("RegionUuid")
                        .HasName("PRIMARY");

                    b.ToTable("regionsettings", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Regionwindlight", b =>
                {
                    b.Property<string>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("region_id")
                        .HasDefaultValueSql("'000000-0000-0000-0000-000000000000'");

                    b.Property<float>("AmbientB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("ambient_b")
                        .HasDefaultValueSql("'0.34999999'");

                    b.Property<float>("AmbientG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("ambient_g")
                        .HasDefaultValueSql("'0.34999999'");

                    b.Property<float>("AmbientI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("ambient_i")
                        .HasDefaultValueSql("'0.34999999'");

                    b.Property<float>("AmbientR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("ambient_r")
                        .HasDefaultValueSql("'0.34999999'");

                    b.Property<float>("BigWaveDirectionX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8)")
                        .HasColumnName("big_wave_direction_x")
                        .HasDefaultValueSql("'1.04999995'");

                    b.Property<float>("BigWaveDirectionY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8)")
                        .HasColumnName("big_wave_direction_y")
                        .HasDefaultValueSql("'-0.41999999'");

                    b.Property<float>("BlueDensityB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("blue_density_b")
                        .HasDefaultValueSql("'0.38000000'");

                    b.Property<float>("BlueDensityG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("blue_density_g")
                        .HasDefaultValueSql("'0.22000000'");

                    b.Property<float>("BlueDensityI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("blue_density_i")
                        .HasDefaultValueSql("'0.38000000'");

                    b.Property<float>("BlueDensityR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("blue_density_r")
                        .HasDefaultValueSql("'0.12000000'");

                    b.Property<float>("BlurMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("blur_multiplier")
                        .HasDefaultValueSql("'0.04000000'");

                    b.Property<float>("CloudColorB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_color_b")
                        .HasDefaultValueSql("'0.41000000'");

                    b.Property<float>("CloudColorG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_color_g")
                        .HasDefaultValueSql("'0.41000000'");

                    b.Property<float>("CloudColorI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_color_i")
                        .HasDefaultValueSql("'0.41000000'");

                    b.Property<float>("CloudColorR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_color_r")
                        .HasDefaultValueSql("'0.41000000'");

                    b.Property<float>("CloudCoverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_coverage")
                        .HasDefaultValueSql("'0.27000001'");

                    b.Property<float>("CloudDensity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_density")
                        .HasDefaultValueSql("'1.00000000'");

                    b.Property<float>("CloudDetailDensity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_detail_density")
                        .HasDefaultValueSql("'0.12000000'");

                    b.Property<float>("CloudDetailX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_detail_x")
                        .HasDefaultValueSql("'1.00000000'");

                    b.Property<float>("CloudDetailY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_detail_y")
                        .HasDefaultValueSql("'0.52999997'");

                    b.Property<float>("CloudScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_scale")
                        .HasDefaultValueSql("'0.41999999'");

                    b.Property<float>("CloudScrollX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,7)")
                        .HasColumnName("cloud_scroll_x")
                        .HasDefaultValueSql("'0.2000000'");

                    b.Property<byte>("CloudScrollXLock")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("cloud_scroll_x_lock");

                    b.Property<float>("CloudScrollY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,7)")
                        .HasColumnName("cloud_scroll_y")
                        .HasDefaultValueSql("'0.0100000'");

                    b.Property<byte>("CloudScrollYLock")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("cloud_scroll_y_lock");

                    b.Property<float>("CloudX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_x")
                        .HasDefaultValueSql("'1.00000000'");

                    b.Property<float>("CloudY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("cloud_y")
                        .HasDefaultValueSql("'0.52999997'");

                    b.Property<float>("DensityMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("density_multiplier")
                        .HasDefaultValueSql("'0.18000001'");

                    b.Property<float>("DistanceMultiplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,6) unsigned")
                        .HasColumnName("distance_multiplier")
                        .HasDefaultValueSql("'0.800000'");

                    b.Property<byte>("DrawClassicClouds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("draw_classic_clouds")
                        .HasDefaultValueSql("'1'");

                    b.Property<float>("EastAngle")
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("east_angle");

                    b.Property<float>("FresnelOffset")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("fresnel_offset")
                        .HasDefaultValueSql("'0.50000000'");

                    b.Property<float>("FresnelScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("fresnel_scale")
                        .HasDefaultValueSql("'0.40000001'");

                    b.Property<float>("HazeDensity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("haze_density")
                        .HasDefaultValueSql("'0.69999999'");

                    b.Property<float>("HazeHorizon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("haze_horizon")
                        .HasDefaultValueSql("'0.19000000'");

                    b.Property<float>("HorizonB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("horizon_b")
                        .HasDefaultValueSql("'0.31999999'");

                    b.Property<float>("HorizonG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("horizon_g")
                        .HasDefaultValueSql("'0.25000000'");

                    b.Property<float>("HorizonI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("horizon_i")
                        .HasDefaultValueSql("'0.31999999'");

                    b.Property<float>("HorizonR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("horizon_r")
                        .HasDefaultValueSql("'0.25000000'");

                    b.Property<float>("LittleWaveDirectionX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8)")
                        .HasColumnName("little_wave_direction_x")
                        .HasDefaultValueSql("'1.11000001'");

                    b.Property<float>("LittleWaveDirectionY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8)")
                        .HasColumnName("little_wave_direction_y")
                        .HasDefaultValueSql("'-1.15999997'");

                    b.Property<uint>("MaxAltitude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("max_altitude")
                        .HasDefaultValueSql("'1605'");

                    b.Property<string>("NormalMapTexture")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("normal_map_texture")
                        .HasDefaultValueSql("'822ded49-9a6c-f61c-cb89-6df54f42cdf4'");

                    b.Property<float>("ReflectionWaveletScale1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,7) unsigned")
                        .HasColumnName("reflection_wavelet_scale_1")
                        .HasDefaultValueSql("'2.0000000'");

                    b.Property<float>("ReflectionWaveletScale2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,7) unsigned")
                        .HasColumnName("reflection_wavelet_scale_2")
                        .HasDefaultValueSql("'2.0000000'");

                    b.Property<float>("ReflectionWaveletScale3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,7) unsigned")
                        .HasColumnName("reflection_wavelet_scale_3")
                        .HasDefaultValueSql("'2.0000000'");

                    b.Property<float>("RefractScaleAbove")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("refract_scale_above")
                        .HasDefaultValueSql("'0.03000000'");

                    b.Property<float>("RefractScaleBelow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("refract_scale_below")
                        .HasDefaultValueSql("'0.20000000'");

                    b.Property<float>("SceneGamma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,7) unsigned")
                        .HasColumnName("scene_gamma")
                        .HasDefaultValueSql("'1.0000000'");

                    b.Property<float>("StarBrightness")
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("star_brightness");

                    b.Property<float>("SunGlowFocus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("sun_glow_focus")
                        .HasDefaultValueSql("'0.10000000'");

                    b.Property<float>("SunGlowSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("sun_glow_size")
                        .HasDefaultValueSql("'1.75000000'");

                    b.Property<float>("SunMoonColorB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("sun_moon_color_b")
                        .HasDefaultValueSql("'0.30000001'");

                    b.Property<float>("SunMoonColorG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("sun_moon_color_g")
                        .HasDefaultValueSql("'0.25999999'");

                    b.Property<float>("SunMoonColorI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("sun_moon_color_i")
                        .HasDefaultValueSql("'0.30000001'");

                    b.Property<float>("SunMoonColorR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("sun_moon_color_r")
                        .HasDefaultValueSql("'0.23999999'");

                    b.Property<float>("SunMoonPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("sun_moon_position")
                        .HasDefaultValueSql("'0.31700000'");

                    b.Property<float>("UnderwaterFogModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,8) unsigned")
                        .HasColumnName("underwater_fog_modifier")
                        .HasDefaultValueSql("'0.25000000'");

                    b.Property<float>("WaterColorB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,6) unsigned")
                        .HasColumnName("water_color_b")
                        .HasDefaultValueSql("'64.000000'");

                    b.Property<float>("WaterColorG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,6) unsigned")
                        .HasColumnName("water_color_g")
                        .HasDefaultValueSql("'38.000000'");

                    b.Property<float>("WaterColorR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,6) unsigned")
                        .HasColumnName("water_color_r")
                        .HasDefaultValueSql("'4.000000'");

                    b.Property<float>("WaterFogDensityExponent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float(9,7) unsigned")
                        .HasColumnName("water_fog_density_exponent")
                        .HasDefaultValueSql("'4.0000000'");

                    b.HasKey("RegionId")
                        .HasName("PRIMARY");

                    b.ToTable("regionwindlight", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.SpawnPoint", b =>
                {
                    b.Property<float>("Distance")
                        .HasColumnType("float");

                    b.Property<float>("Pitch")
                        .HasColumnType("float");

                    b.Property<string>("RegionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("RegionID");

                    b.Property<float>("Yaw")
                        .HasColumnType("float");

                    b.HasIndex(new[] { "RegionId" }, "RegionID");

                    b.ToTable("spawn_points", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb3");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb3_general_ci");
                });

            modelBuilder.Entity("OpenSim.Data.Model.Region.Terrain", b =>
                {
                    b.Property<byte[]>("Heightfield")
                        .HasColumnType("longblob");

                    b.Property<string>("RegionUuid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RegionUUID");

                    b.Property<int?>("Revision")
                        .HasColumnType("int");

                    b.ToTable("terrain", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "latin1");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "latin1_swedish_ci");
                });
#pragma warning restore 612, 618
        }
    }
}
