<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>OpenSim.Server.Handlers</AssemblyTitle>
    <Company>http://opensimulator.org</Company>
    <Product>OpenSim</Product>
    <Copyright>OpenSimulator developers</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DotNetOpenId" HintPath="../../Library/DotNetOpenId.dll" />
    <Reference Include="Nini" HintPath="../../Library/Nini.dll" />
    <Reference Include="OpenMetaverse" HintPath="../../Library/OpenMetaverse.dll" />
    <Reference Include="OpenMetaverse.StructuredData" HintPath="../../Library/OpenMetaverse.StructuredData.dll" />
    <Reference Include="OpenMetaverseTypes" HintPath="../../Library/OpenMetaverseTypes.dll" />
    <Reference Include="xmlrpc" HintPath="../../Library/xmlrpc.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Source/OpenSim.Framework/OpenSim.Framework.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Console/OpenSim.Framework.Console.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Framework.Servers.HttpServer/OpenSim.Framework.Servers.HttpServer.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Server.Base/OpenSim.Server.Base.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Services.Base/OpenSim.Services.Base.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Services.Interfaces/OpenSim.Services.Interfaces.csproj" />
    <ProjectReference Include="../../Source/OpenSim.Services.UserAccountService/OpenSim.Services.UserAccountService.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.0" />
    <PackageReference Include="Mono.Addins" Version="1.4.1" />
    <PackageReference Include="Mono.Addins.CecilReflector" Version="1.4.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.5" />
  </ItemGroup>

</Project>
