<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <AssemblyTitle>OpenSim.Framework</AssemblyTitle>
      <Company>http://opensimulator.org</Company>
      <Product>OpenSim.Framework</Product>
      <Copyright>Copyright (c) OpenSimulator.org Developers 2007-2009</Copyright>
      <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup> 
  <ItemGroup>
    <Reference Include="LukeSkywalker.IPNetwork" HintPath="../../Library/LukeSkywalker.IPNetwork.dll" />
    <Reference Include="Nini" HintPath="../../Library/Nini.dll" />
    <Reference Include="OpenMetaverse" HintPath="../../Library/OpenMetaverse.dll" />
    <Reference Include="OpenMetaverse.StructuredData" HintPath="../../Library/OpenMetaverse.StructuredData.dll" />
    <Reference Include="OpenMetaverseTypes" HintPath="../../Library/OpenMetaverseTypes.dll" />
    <Reference Include="xmlrpc" HintPath="../../Library/xmlrpc.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../ThirdParty/SmartThreadPool/SmartThreadPool.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
    <PackageReference Include="CoreJ2K.Skia" Version="2.1.2.38" />
    <PackageReference Include="log4net" Version="3.3.0" />
    <PackageReference Include="McMaster.NETCore.Plugins" Version="2.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.5" />
  </ItemGroup>

</Project>
