<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>Warp3D</AssemblyTitle>
    <Company>http://utopiaskye.com</Company>
    <SignAssembly>true</SignAssembly>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
    <PackageReference Include="CoreJ2K.Skia" Version="2.3.3.91" />
    <PackageReference Include="OpenMetaverse.Rendering.Meshmerizer" Version="1.0.6" />
  </ItemGroup>

</Project>
