name: dotnet console app build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Display dotnet version
      run: dotnet --version

    - name: Cache NuGet Packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }} restore-keys: | ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore ./Tranquillity.sln

    - name: Build
      run: dotnet build ./Tranquillity.sln --configuration Release --no-restore

#    - name: Tests
#      run: dotnet test ./Tranquillity.sln --verbosity normal

    - name: Publish GridServer for Linux x64
      run: dotnet publish Source/OpenSim.Server.GridServer/OpenSim.Server.GridServer.csproj -c Release -r linux-x64 --self-contained false -o ./publish/linux-x64/gridserver

    - name: Publish RegionServer for Linux x64
      run: dotnet publish Source/OpenSim.Server.RegionServer/OpenSim.Server.RegionServer.csproj -c Release -r linux-x64 --self-contained false -o ./publish/linux-x64/regionserver

    - name: Publish MoneyServer for Linux x64
      run: dotnet publish Source/OpenSim.Server.MoneyServer/OpenSim.Server.MoneyServer.csproj -c Release -r linux-x64 --self-contained false -o ./publish/linux-x64/moneyserver

    - name: Publish GridServer for Windows x64
      run: dotnet publish Source/OpenSim.Server.GridServer/OpenSim.Server.GridServer.csproj -c Release -r win-x64 --self-contained false -o ./publish/win-x64/gridserver

    - name: Publish RegionServer for Windows x64
      run: dotnet publish Source/OpenSim.Server.RegionServer/OpenSim.Server.RegionServer.csproj -c Release -r win-x64 --self-contained false -o ./publish/win-x64/regionserver

    - name: Publish MoneyServer for Windows x64
      run: dotnet publish Source/OpenSim.Server.MoneyServer/OpenSim.Server.MoneyServer.csproj -c Release -r win-x64 --self-contained false -o ./publish/win-x64/moneyserver
