name: dotnet console app build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Display dotnet version
      run: dotnet --version

    - name: Restore dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet restore ./Tranquillity.sln

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet build ./Tranquillity.sln --configuration Release --no-restore

#    - name: Tests
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
#      run: dotnet test ./Tranquillity.sln --verbosity normal

    - name: Pack library projects
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: |
        mkdir -p ./nupkgs
        for proj in \
          Source/OpenSim.Data.Model/OpenSim.Data.Model.csproj; do
          dotnet pack "$proj" -c Release --no-build --include-symbols -o ./nupkgs
        done

    - name: Publish packages to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: |
        dotnet nuget push "./nupkgs/*.nupkg" \
          --api-key "${{ secrets.GITHUB_TOKEN }}" \
          --source "github" \
          --skip-duplicate
          
    # Publish GridServer for Linux x64
    - name: Publish GridServer for Linux x64
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet publish ./Source/OpenSim.Server.GridServer/OpenSim.Server.GridServer.csproj -c Release -r linux-x64 -o ./publish/linux-x64/OpenSim.Server.GridServer

    # Publish RegionServer for Linux x64
    - name: Publish RegionServer for Linux x64
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet publish ./Source/OpenSim.Server.RegionServer/OpenSim.Server.RegionServer.csproj -c Release -r linux-x64 -o ./publish/linux-x64/OpenSim.Server.RegionServer
    
    # Publish MoneyServer for Linux x64
    - name: Publish MoneyServer for Linux x64
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet publish ./Source/OpenSim.Server.MoneyServer/OpenSim.Server.MoneyServer.csproj -c Release -r linux-x64 -o ./publish/linux-x64/OpenSim.Server.MoneyServer

    # Upload Project Linux Artifacts
    - name: Upload Linux Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-x64-artifacts
        path: ./publish/linux-x64

    # Publish GridServer for Windows x64
    - name: Publish GridServer for Windows x64
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet publish ./Source/OpenSim.Server.GridServer/OpenSim.Server.GridServer.csproj -c Release -r win-x64 -o ./publish/win-x64/OpenSim.Server.GridServer
  
    # Publish RegionServer for Windows x64
    - name: Publish RegionServer for Windows x64
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet publish ./Source/OpenSim.Server.RegionServer/OpenSim.Server.RegionServer.csproj -c Release -r win-x64 -o ./publish/win-x64/OpenSim.Server.RegionServer
  
    # Publish MoneyServer for Windows x64
    - name: Publish MoneyServer for Windows x64
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet publish ./Source/OpenSim.Server.MoneyServer/OpenSim.Server.MoneyServer.csproj -c Release -r win-x64 -o ./publish/win-x64/OpenSim.Server.MoneyServer

    # Upload Windows Build Artifacts
    - name: Upload Windows Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win-x64-artifacts
        path: ./publish/win-x64
