name: dotnet console app build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Display dotnet version
      run: dotnet --version

    - name: Restore dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet restore ./Tranquillity.sln

    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: dotnet build ./Tranquillity.sln --configuration Release --no-restore

#    - name: Tests
#      env:
#        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
#      run: dotnet test ./Tranquillity.sln --verbosity normal
